name: koperasi_central
description: A new Flutter project.

publish_to: 'none'

version: 0.5.5+9

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6
  http: ^0.13.5
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  firebase_core: ^2.4.1
  flutter_exif_rotation: ^0.5.1
  flutter_launcher_icons: "^0.11.0"
  auto_start_flutter: ^0.1.1
  google_nav_bar: ^5.0.6
  intl: ^0.18.1
  dropdown_search: ^2.0.0
  file_picker: ^5.3.1
  flutter_pdfview: ^1.3.1
  path_provider: ^2.1.0
  shimmer: ^3.0.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_new.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true

flutter:

  fonts:
    - family: Mclaren
      fonts:
        - asset: assets/fonts/mcLaren.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Reg.ttf

  uses-material-design: true

  assets:
    - assets/
